app_dev:
  image: minity/php54-webapp-dev
  volumes:
    - .:/src
  external_links:
    - mysql:db
  environment:
    - VIRTUAL_HOST=autocrm2-1c.dev # см. https://hub.docker.com/r/jwilder/nginx-proxy/
